export type MusicArtwork = {
  title: string;
  artist: string;
  year: number;
  cover: string;
};

export const musicArtworks = [
  { title: "Free Bird", artist: "Lynyrd Skynyrd", year: 1973, cover: "/images/covers/01-free-bird.webp" },
  { title: "End of Beginning", artist: "Djo", year: 2022, cover: "/images/covers/02-end-of-beginning.webp" },
  { title: "Manchild", artist: "Sabrina Carpenter", year: 2025, cover: "/images/covers/03-manchild.webp" },
  { title: "Short n' Sweet", artist: "Sabrina Carpenter", year: 2024, cover: "/images/covers/04-short-n-sweet.webp" },
  { title: "OK Computer", artist: "Radiohead", year: 1997, cover: "/images/covers/05-ok-computer.webp" },
  { title: "Pablo Honey", artist: "Radiohead", year: 1993, cover: "/images/covers/06-pablo-honey.webp" },
  { title: "The Bends", artist: "Radiohead", year: 1995, cover: "/images/covers/07-the-bends.webp" },
  { title: "Thriller", artist: "Michael Jackson", year: 1982, cover: "/images/covers/08-thriller.webp" },
  { title: "Modal Soul", artist: "Nujabes", year: 2005, cover: "/images/covers/09-modal-soul.webp" },
  { title: "Luv(sic) Hexalogy", artist: "Nujabes", year: 2015, cover: "/images/covers/10-luv-sic-hexalogy.webp" },
  { title: "Imaginal Disk", artist: "Magdalena Bay", year: 2024, cover: "/images/covers/11-imaginal-disk.webp" },
  { title: "Begin Again (Music from and Inspired by the Original Motion Picture)", artist: "Various Artists", year: 2014, cover: "/images/covers/12-begin-again-soundtrack.webp" },
  { title: "杰伦", artist: "周杰伦", year: 2000, cover: "/images/covers/13-jay.webp" },
  { title: "八度空间", artist: "周杰伦", year: 2002, cover: "/images/covers/14-the-eight-dimensions.webp" },
  { title: "跨时代", artist: "周杰伦", year: 2010, cover: "/images/covers/15-the-era.webp" },
  { title: "Bewitched", artist: "Laufey", year: 2023, cover: "/images/covers/16-bewitched.webp" },
  { title: "Syro", artist: "Aphex Twin", year: 2014, cover: "/images/covers/17-syro.webp" },
  { title: "SOS", artist: "SZA", year: 2022, cover: "/images/covers/18-sos.webp" },
  { title: "I'm O.K.", artist: "陶喆", year: 1999, cover: "/images/covers/19-im-ok.webp" },
  { title: "黑色柳丁", artist: "陶喆", year: 2002, cover: "/images/covers/20-black-tangerine.webp" },
  { title: "爱，很简单", artist: "陶喆", year: 1997, cover: "/images/covers/21-i-love-you.webp" },
  { title: "back to friends", artist: "sombr", year: 2024, cover: "/images/covers/22-back-to-friends.webp" },
  { title: "The Dark Side of the Moon", artist: "Pink Floyd", year: 1973, cover: "/images/covers/23-the-dark-side-of-the-moon.webp" },
  { title: "Wish You Were Here", artist: "Pink Floyd", year: 1975, cover: "/images/covers/24-wish-you-were-here.webp" },
  { title: "The Wall", artist: "Pink Floyd", year: 1979, cover: "/images/covers/25-the-wall.webp" },
  { title: "Nevermind (Remastered)", artist: "Nirvana", year: 1991, cover: "/images/covers/26-nevermind.webp" },
  { title: "Another One Bites the Dust", artist: "Queen", year: 1980, cover: "/images/covers/27-another-one-bites-the-dust.webp" },
  { title: "Goodbye Yellow Brick Road", artist: "Elton John", year: 1973, cover: "/images/covers/28-goodbye-yellow-brick-road.webp" },
  { title: "Notes on a Conditional Form", artist: "The 1975", year: 2020, cover: "/images/covers/29-notes-on-a-conditional-form.webp" },
  { title: "Robbers", artist: "The 1975", year: 2013, cover: "/images/covers/30-robbers.webp" },
  { title: "I Still Haven't Found What I'm Looking For", artist: "U2", year: 1987, cover: "/images/covers/31-i-still-havent-found.webp" },
  { title: "Bullet the Blue Sky", artist: "U2", year: 1987, cover: "/images/covers/32-bullet-the-blue-sky.webp" },
  { title: "吉他手", artist: "陈绮贞", year: 2002, cover: "/images/covers/33-guitar-player.webp" },
  { title: "沙发海", artist: "陈绮贞", year: 2018, cover: "/images/covers/34-sofa-sea.webp" },
  { title: "旅行的意义", artist: "陈绮贞", year: 2004, cover: "/images/covers/35-the-meaning-of-travel.webp" },
  { title: "After Hours", artist: "The Weeknd", year: 2020, cover: "/images/covers/36-after-hours.webp" },
  { title: "Starboy", artist: "The Weeknd", year: 2016, cover: "/images/covers/37-starboy.webp" },
  { title: "Dawn FM", artist: "The Weeknd", year: 2022, cover: "/images/covers/38-dawn-fm.webp" },
  { title: "Hurry Up Tomorrow", artist: "The Weeknd", year: 2025, cover: "/images/covers/39-hurry-up-tomorrow.webp" },
  { title: "Weightless", artist: "Arlo Parks", year: 2023, cover: "/images/covers/40-weightless.webp" },
  { title: "Black Dog", artist: "Arlo Parks", year: 2020, cover: "/images/covers/41-black-dog.webp" },
  { title: "On & On", artist: "Erykah Badu", year: 1996, cover: "/images/covers/42-on-and-on.webp" },
  { title: "365", artist: "Charli xcx", year: 2024, cover: "/images/covers/43-365.webp" },
  { title: "Currents", artist: "Tame Impala", year: 2015, cover: "/images/covers/44-currents.webp" },
  { title: "Bones", artist: "Low Roar", year: 2017, cover: "/images/covers/45-bones.webp" },
  { title: "Viva La Vida", artist: "Coldplay", year: 2008, cover: "/images/covers/46-viva-la-vida.webp" },
  { title: "I Just Called to Say I Love You", artist: "Stevie Wonder", year: 1984, cover: "/images/covers/47-i-just-called-to-say-i-love-you.webp" },
  { title: "Fresh", artist: "Kool & The Gang", year: 1984, cover: "/images/covers/48-fresh.webp" },
  { title: "Doo-Wops & Hooligans", artist: "Bruno Mars", year: 2010, cover: "/images/covers/49-doo-wops-and-hooligans.webp" },
  { title: "Unorthodox Jukebox", artist: "Bruno Mars", year: 2012, cover: "/images/covers/50-unorthodox-jukebox.webp" },
  { title: "From the Start", artist: "Laufey", year: 2023, cover: "/images/covers/51-from-the-start.webp" },
  { title: "Love Rollercoaster", artist: "Ohio Players", year: 1975, cover: "/images/covers/52-love-rollercoaster.webp" },
  { title: "Good Times", artist: "Aretha Franklin", year: 1967, cover: "/images/covers/53-good-times.webp" },
  { title: "梦蝴蝶", artist: "方大同", year: 2016, cover: "/images/covers/54-dream-butterfly.webp" },
  { title: "Didn't Cha Know", artist: "Erykah Badu", year: 2000, cover: "/images/covers/55-didnt-cha-know.webp" },
  { title: "Maxwell's Urban Hang Suite", artist: "Maxwell", year: 1996, cover: "/images/covers/56-maxwells-urban-hang-suite.webp" },
  { title: "Hits Different", artist: "Taylor Swift", year: 2022, cover: "/images/covers/57-hits-different.webp" },
  { title: "Style", artist: "Taylor Swift", year: 2014, cover: "/images/covers/58-style.webp" },
  { title: "Norman Fucking Rockwell!", artist: "Lana Del Rey", year: 2019, cover: "/images/covers/59-norman-fucking-rockwell.webp" },
  { title: "September", artist: "Earth, Wind & Fire", year: 1978, cover: "/images/covers/60-september.webp" },
] satisfies readonly MusicArtwork[];
